rs-group-name = "Three-Tier-K8s-RG-a"
location      = "Canada East"
ssh_key       = "./aks_vm.pub"
cluster-name  = "Three-Tier-K8s-Cluster"
acr-name      = "frontendabdou8765"
acr-name2     = "backendabdou34567"
# role_id   = "${ROLE_ID}"
# secret_id = "${SECRET_ID}"